# Generated by Django 5.1.7 on 2025-03-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_client_phone_alter_lawyer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('OPEN', 'مفتوح'), ('CLOSED', 'مغلق')], max_length=10),
        ),
    ]
