# Generated by Django 5.0.13 on 2025-03-19 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_client_phone_alter_lawyer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='case_documents/%Y/%m/%d/')),
                ('category', models.CharField(choices=[('CONTRACT', 'Contract'), ('COURT_FILING', 'Court Filing'), ('CORRESPONDENCE', 'Correspondence'), ('EVIDENCE', 'Evidence'), ('REPORT', 'Report'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case')),
            ],
        ),
    ]
