# Generated by Django 5.1.7 on 2025-03-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
